[package]
name = "mfrc522"
version = "0.8.0"
authors = ["Jonas Spanoghe <jonas@spanoghe.net>", "Jorge Aparicio <jorge@japaric.io>"]
edition = "2021"
description = "A platform agnostic driver to interface the MFRC522 (RFID reader/writer)"
documentation = "https://docs.rs/mfrc522"
license = "MIT OR Apache-2.0"
repository = "https://gitlab.com/jspngh/mfrc522"
homepage = "https://gitlab.com/jspngh/mfrc522"
keywords = ["rfid", "mfrc522", "embedded-hal", "mifare"]
categories = ["embedded", "hardware-support", "no-std"]

[features]
std = []
eh02 = ["dep:embedded-hal-02"]

[dependencies]
embedded-hal-02 = { package = "embedded-hal", version = "0.2", optional = true }
embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
heapless = "0.8"

[dev-dependencies]
embedded-hal-mock = { version = "0.10", features = ["eh1"] }
