[package]
name = "mfrc522-async"
version = "0.1.0"
authors = [
  "Adam Szalkowski <adam@szalkowski.de>",
  "Jonas Spanoghe <jonas@spanoghe.net>",
  "Jorge Aparicio <jorge@japaric.io>",
]
edition = "2024"
description = "A platform agnostic driver to interface the MFRC522 (RFID reader/writer)"
documentation = "https://docs.rs/mfrc522-async"
license = "MIT OR Apache-2.0"
repository = "https://github.com/butzist/mfrc522-async"
homepage = "https://gitlab.com/butzist/mfrc522-async"
keywords = ["rfid", "mfrc522", "embedded-hal", "mifare"]
categories = ["embedded", "hardware-support", "no-std"]

[dependencies]
embedded-hal-async = "1"
embassy-futures = { version = "0.1", default-features = false }
embassy-time = { version = "0.5", default-features = false }

defmt = { version = "1", optional = true }

[dev-dependencies]
embedded-hal = "1"
embedded-hal-mock = { version = "0.11", default-features = false, features = [
  "eh1",
  "embedded-hal-async",
] }
futures = { version = "0.3", default-features = false }
tokio = { version = "1", features = ["rt", "macros"] }

[features]
default = []
defmt = ["dep:defmt"]
