[package]
name = "mfrc522-rpi4"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
embedded-hal = "1.0"
linux-embedded-hal = "0.4.0"
embedded-hal-bus = "0.2.0"
anyhow = "1.0"

mfrc522 = { version = "0.7", features = ["std"] }

[patch.crates-io]
mfrc522 = { path = "../../" }
